"""Update models with anonymity and timestamps

Revision ID: 4b16424da1b7
Revises: d5a0c9ca3896
Create Date: 2026-01-27 21:36:09.035220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b16424da1b7'
down_revision: Union[str, Sequence[str], None] = 'd5a0c9ca3896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add nullable column
    op.add_column('posts', sa.Column('owner_username', sa.String(length=255), nullable=True))
    
    # Copy data from owner_id to owner_username via JOIN
    op.execute("""
        UPDATE posts 
        SET owner_username = users.username 
        FROM users 
        WHERE posts.owner_id = users.id
    """)
    
    # Make column NOT NULL after data is populated
    op.alter_column('posts', 'owner_username', nullable=False)
    
    # Drop old foreign key and index
    op.drop_index(op.f('ix_posts_owner_id'), table_name='posts')
    op.drop_constraint(op.f('posts_owner_id_fkey'), 'posts', type_='foreignkey')
    
    # Add new index and foreign key
    op.create_index(op.f('ix_posts_owner_username'), 'posts', ['owner_username'], unique=False)
    op.create_foreign_key(None, 'posts', 'users', ['owner_username'], ['username'])
    
    # Finally drop old column
    op.drop_column('posts', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_owner_id_fkey'), 'posts', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_posts_owner_username'), table_name='posts')
    op.create_index(op.f('ix_posts_owner_id'), 'posts', ['owner_id'], unique=False)
    op.drop_column('posts', 'owner_username')
    # ### end Alembic commands ###
