"""Change all user references to username

Revision ID: bc162c604430
Revises: 4b16424da1b7
Create Date: 2026-01-27 22:26:12.107286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc162c604430'
down_revision: Union[str, Sequence[str], None] = '4b16424da1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_username', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_comments_owner_id'), table_name='comments')
    op.create_index(op.f('ix_comments_owner_username'), 'comments', ['owner_username'], unique=False)
    op.drop_constraint(op.f('comments_owner_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['owner_username'], ['username'])
    op.drop_column('comments', 'owner_id')
    op.add_column('files', sa.Column('uploader_username', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_files_uploader_id'), table_name='files')
    op.create_index(op.f('ix_files_uploader_username'), 'files', ['uploader_username'], unique=False)
    op.drop_constraint(op.f('files_uploader_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['uploader_username'], ['username'])
    op.drop_column('files', 'uploader_id')
    op.add_column('messages', sa.Column('sender_username', sa.String(length=255), nullable=False))
    op.add_column('messages', sa.Column('recipient_username', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.create_index(op.f('ix_messages_recipient_username'), 'messages', ['recipient_username'], unique=False)
    op.create_index(op.f('ix_messages_sender_username'), 'messages', ['sender_username'], unique=False)
    op.drop_constraint(op.f('messages_recipient_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['recipient_username'], ['username'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_username'], ['username'])
    op.drop_column('messages', 'recipient_id')
    op.drop_column('messages', 'sender_id')
    op.add_column('reports', sa.Column('reporter_username', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.create_index(op.f('ix_reports_reporter_username'), 'reports', ['reporter_username'], unique=False)
    op.drop_constraint(op.f('reports_reporter_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['reporter_username'], ['username'])
    op.drop_column('reports', 'reporter_id')
    op.add_column('votes', sa.Column('username', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.create_index(op.f('ix_votes_username'), 'votes', ['username'], unique=False)
    op.drop_constraint(op.f('votes_user_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['username'], ['username'])
    op.drop_column('votes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_user_id_fkey'), 'votes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_votes_username'), table_name='votes')
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    op.drop_column('votes', 'username')
    op.add_column('reports', sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_reporter_id_fkey'), 'reports', 'users', ['reporter_id'], ['id'])
    op.drop_index(op.f('ix_reports_reporter_username'), table_name='reports')
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.drop_column('reports', 'reporter_username')
    op.add_column('messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_recipient_id_fkey'), 'messages', 'users', ['recipient_id'], ['id'])
    op.drop_index(op.f('ix_messages_sender_username'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_username'), table_name='messages')
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.drop_column('messages', 'recipient_username')
    op.drop_column('messages', 'sender_username')
    op.add_column('files', sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_uploader_id_fkey'), 'files', 'users', ['uploader_id'], ['id'])
    op.drop_index(op.f('ix_files_uploader_username'), table_name='files')
    op.create_index(op.f('ix_files_uploader_id'), 'files', ['uploader_id'], unique=False)
    op.drop_column('files', 'uploader_username')
    op.add_column('comments', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_owner_id_fkey'), 'comments', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_comments_owner_username'), table_name='comments')
    op.create_index(op.f('ix_comments_owner_id'), 'comments', ['owner_id'], unique=False)
    op.drop_column('comments', 'owner_username')
    # ### end Alembic commands ###
