"""Initial migration

Revision ID: d5a0c9ca3896
Revises: 
Create Date: 2026-01-27 10:46:53.993473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a0c9ca3896'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add username column as nullable first
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    
    # Set default usernames for existing users
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE users SET username = 'user_' || id WHERE username IS NULL"))
    
    # Make it NOT NULL and add unique constraint
    op.alter_column('users', 'username', nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
